set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RADXA_SYSROOT "/home/user/sysroots/radxa" CACHE PATH "Radxa target sysroot")
set(CMAKE_SYSROOT "${RADXA_SYSROOT}")
set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH "${RADXA_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${RADXA_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${RADXA_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${RADXA_SYSROOT}/usr/lib/pkgconfig:${RADXA_SYSROOT}/usr/share/pkgconfig"
)
